// SPDX-License-Identifier: Apache-2.0 OR MIT
#include "vec_rd.h"

#include <cstdio>
#include <cstring>
#include <utility>

// Generated by kernels/drape/gen.sh into the build directory: one byte array
// per SPIR-V kernel plus find(name).
#include "drape_kernels.inc"

namespace {

// The kernels this backend dispatches. dot_reduce is not among them: a dot
// is lb_multi_dot with one column (same df32 sum), which takes a destination
// offset, so every scalar of a phase lands in one buffer and one readback.
const char *const kKernels[] = {
	"lb_box_project", "lb_pg_inf", "lb_step_max", "lb_multi_dot", "lb_compact", "lb_ring_store",
	"lb_apply_m", "lb_cauchy", "lb_subspace", "saxpby",
};

const cloth::drape_table::KernelDesc *table_find(const char *name) {
	for (uint32_t i = 0; i < cloth::drape_table::kNumKernels; ++i) {
		if (std::strcmp(cloth::drape_table::kKernels[i].name, name) == 0) {
			return &cloth::drape_table::kKernels[i];
		}
	}
	return nullptr;
}

uint32_t fbits(float f) {
	uint32_t u;
	std::memcpy(&u, &f, 4);
	return u;
}

// One op as the GPU sees it: kernel, binding name -> buffer, params words,
// workgroups.
struct Dispatch {
	const char *kernel = nullptr;
	std::vector<std::pair<const char *, int>> binds;
	std::vector<uint32_t> params;
	uint32_t groups = 1;
};

Dispatch describe(const lbv::Op &o, uint32_t n, uint32_t mc) {
	using lbv::Op;
	Dispatch d;
	const uint32_t perElem = (n + 255) / 256;
	switch (o.kind) {
		case Op::BoxProject:
			d.kernel = "lb_box_project";
			d.binds = { { "x", o.a }, { "lb", lbv::LB }, { "ub", lbv::UB } };
			d.params = { n };
			d.groups = perElem;
			break;
		case Op::PgInf:
			d.kernel = "lb_pg_inf";
			d.binds = { { "x", o.a }, { "g", o.b }, { "lb", lbv::LB }, { "ub", lbv::UB }, { "dst", lbv::SC } };
			d.params = { n, o.u0 };
			d.groups = 1; // one workgroup, grid-strided, tree-reduced
			break;
		case Op::StepMax:
			d.kernel = "lb_step_max";
			d.binds = { { "x", o.a }, { "d", o.b }, { "lb", lbv::LB }, { "ub", lbv::UB }, { "dst", lbv::SC } };
			d.params = { n, o.u0 };
			d.groups = 1;
			break;
		case Op::MultiDot:
			d.kernel = "lb_multi_dot";
			d.binds = { { "a", o.a }, { "vv", o.b }, { "dst", o.c } };
			d.params = { n, o.u0, 0u, o.u1 ? o.u1 : n, 0u, o.u3 };
			d.groups = o.u0; // one workgroup per column
			break;
		case Op::Compact:
			d.kernel = "lb_compact";
			d.binds = { { "dots", lbv::DOTS }, { "st", lbv::ST }, { "bf", lbv::BF } };
			d.params = { mc, o.u0 };
			break;
		case Op::RingStore:
			d.kernel = "lb_ring_store";
			d.binds = { { "st", lbv::ST }, { "s", lbv::SV }, { "y", lbv::YV }, { "S", lbv::SM }, { "Y", lbv::YM } };
			d.params = { n };
			d.groups = perElem;
			break;
		case Op::ApplyM:
			d.kernel = "lb_apply_m";
			d.binds = { { "st", lbv::ST }, { "bf", lbv::BF }, { "vin", lbv::VIN }, { "vout", lbv::VOUT } };
			d.params = { mc, o.u0, o.u1 };
			break;
		case Op::Cauchy:
			d.kernel = "lb_cauchy";
			d.binds = { { "x", lbv::X }, { "g", lbv::G }, { "lb", lbv::LB }, { "ub", lbv::UB }, { "S", lbv::SM },
				{ "Y", lbv::YM }, { "st", lbv::ST }, { "bf", lbv::BF }, { "xcp", lbv::XCP }, { "vecc", lbv::VECC },
				{ "wk", lbv::WK }, { "iset", lbv::ISET } };
			d.params = { n, mc };
			break;
		case Op::Subspace:
			d.kernel = "lb_subspace";
			d.binds = { { "x", lbv::X }, { "g", lbv::G }, { "lb", lbv::LB }, { "ub", lbv::UB }, { "S", lbv::SM },
				{ "Y", lbv::YM }, { "st", lbv::ST }, { "bf", lbv::BF }, { "xcp", lbv::XCP }, { "vecc", lbv::VECC },
				{ "iset", lbv::ISET }, { "drt", lbv::D }, { "wk", lbv::WK } };
			d.params = { n, mc, o.u0 };
			break;
		case Op::Saxpby:
			d.kernel = "saxpby";
			d.binds = { { "x", o.a }, { "y", o.b }, { "dst", o.c } };
			d.params = { n, fbits(o.fa), fbits(o.fb) };
			d.groups = perElem;
			break;
	}
	return d;
}

} // namespace

VecRd::VecRd(rdc::Device &dev) :
		d_(dev) {
	ok_ = load_kernels();
}

VecRd::~VecRd() {
	if (pending_) {
		sync();
	}
	free_sites();
	free_buffers();
	for (auto &kv : kernels_) {
		d_.free_rid(kv.second.pipeline);
		d_.free_rid(kv.second.shader);
	}
}

bool VecRd::load_kernels() {
	if (!d_.ok()) {
		err_ = "no RenderingDevice";
		return false;
	}
	for (const char *name : kKernels) {
		const cloth::drape_table::KernelDesc *desc = table_find(name);
		const drape_kernels::Entry *bytes = drape_kernels::find(name);
		if (desc == nullptr || bytes == nullptr) {
			err_ = std::string("kernel missing from table or embed: ") + name;
			return false;
		}
		Kernel k;
		k.desc = desc;
		k.shader = d_.shader_from_spirv(bytes->bytes, bytes->size);
		if (k.shader.index == 0) {
			err_ = std::string(name) + ": " + d_.error();
			return false;
		}
		k.pipeline = d_.compute_pipeline(k.shader);
		if (k.pipeline.index == 0) {
			err_ = std::string(name) + ": " + d_.error();
			return false;
		}
		kernels_[name] = k;
	}
	return true;
}

void VecRd::free_sites() {
	// A set whose buffer was freed went with it on the Godot side; either way
	// its permanent slot is released (rd_compute.h).
	for (auto &kv : sites_) {
		if (kv.second.set.index != 0) {
			if (d_.uniform_set_valid(kv.second.set)) {
				d_.free_rid(kv.second.set);
			} else {
				d_.forget(kv.second.set);
			}
		}
		if (kv.second.params.index != 0) {
			d_.free_rid(kv.second.params);
		}
	}
	sites_.clear();
}

void VecRd::free_buffers() {
	for (int b = 0; b < lbv::kNumBufs; ++b) {
		if (bufs_[b].index != 0) {
			d_.free_rid(bufs_[b]);
		}
		bufs_[b] = ::RID();
		words_[b] = 0;
	}
}

bool VecRd::setup(uint32_t n, uint32_t mcap, std::string &err) {
	if (!ok_) {
		err = "vec rd: " + err_;
		return false;
	}
	if (n == 0 || mcap == 0 || mcap > lbv::kMaxHistory) {
		err = "vec rd: need n > 0 and 0 < m <= 16";
		return false;
	}
	if (pending_) {
		sync();
	}
	// Sets name buffers: drop them before the buffers go.
	free_sites();
	free_buffers();
	n_ = n;
	mc_ = mcap;
	for (int b = 0; b < lbv::kNumBufs; ++b) {
		words_[b] = lbv::buf_words(lbv::Buf(b), n, mcap);
		bufs_[b] = d_.storage_buffer(words_[b] * 4, nullptr);
		if (bufs_[b].index == 0) {
			err = "vec rd: storage_buffer: " + d_.error();
			return false;
		}
	}
	return true;
}

bool VecRd::upload(lbv::Buf b, const void *data, size_t words, size_t off) {
	if (off + words > words_[b]) {
		err_ = "vec rd: upload past the end of buffer " + std::to_string(int(b));
		return false;
	}
	if (pending_) {
		sync();
	}
	if (!d_.buffer_update(bufs_[b], off * 4, words * 4, data)) {
		err_ = "vec rd: buffer_update: " + d_.error();
		return false;
	}
	return true;
}

bool VecRd::read(lbv::Buf b, void *out, size_t words, size_t off) {
	if (off + words > words_[b]) {
		err_ = "vec rd: read past the end of buffer " + std::to_string(int(b));
		return false;
	}
	if (pending_) {
		sync();
	}
	const std::vector<uint8_t> bytes = d_.buffer_get(bufs_[b], off * 4, words * 4);
	if (bytes.size() < words * 4) {
		err_ = "vec rd: buffer_get: " + d_.error();
		return false;
	}
	std::memcpy(out, bytes.data(), words * 4);
	return true;
}

void VecRd::sync() {
	if (!pending_) {
		return;
	}
	d_.sync();
	pending_ = false;
}

bool VecRd::run(const std::vector<lbv::Op> &ops) {
	if (!ok_ || n_ == 0) {
		err_ = "vec rd: not set up";
		return false;
	}
	if (pending_) {
		sync();
	}
	// Pass 1, before the list: every site's params block and uniform set,
	// and every params write (buffer_update is refused inside a list).
	struct Rec {
		const Kernel *k;
		::RID set;
		uint32_t groups;
	};
	std::vector<Rec> recs;
	recs.reserve(ops.size());
	std::map<std::string, const lbv::Op *> dynSeen;
	for (const lbv::Op &o : ops) {
		const Dispatch dd = describe(o, n_, mc_);
		auto kit = kernels_.find(dd.kernel);
		if (kit == kernels_.end()) {
			err_ = std::string("vec rd: no kernel ") + dd.kernel;
			return false;
		}
		const Kernel &k = kit->second;
		std::vector<uint32_t> words = dd.params;
		words.resize((words.size() + 3) / 4 * 4, 0u); // std140 blocks round to 16 bytes
		char key[256];
		int at = std::snprintf(key, sizeof key, "%s|", dd.kernel);
		for (const auto &b : dd.binds) {
			at += std::snprintf(key + at, sizeof key - at, "%d,", b.second);
		}
		std::string skey = key;
		if (o.dyn) {
			skey += "|dyn";
			auto seen = dynSeen.find(skey);
			if (seen != dynSeen.end() && (seen->second->fa != o.fa || seen->second->fb != o.fb)) {
				err_ = "vec rd: a dynamic site is used twice in one phase with different params: " + skey;
				return false;
			}
			dynSeen[skey] = &o;
		} else {
			for (uint32_t w : dd.params) {
				char h[12];
				std::snprintf(h, sizeof h, "|%08x", w);
				skey += h;
			}
		}
		auto it = sites_.find(skey);
		if (it == sites_.end()) {
			Site s;
			s.words = words;
			s.params = d_.uniform_buffer(words.size() * 4, words.data());
			if (s.params.index == 0) {
				err_ = std::string("vec rd: uniform_buffer for ") + dd.kernel + ": " + d_.error();
				return false;
			}
			std::vector<rdc::Binding> rb;
			for (uint32_t bi = 0; bi < k.desc->nBindings; ++bi) {
				const cloth::drape_table::BindingDesc &bd = k.desc->bindings[bi];
				::RID rid;
				if (int32_t(bd.binding) == k.desc->paramsBinding) {
					rid = s.params;
				} else {
					for (const auto &nb : dd.binds) {
						if (std::strcmp(nb.first, bd.name) == 0) {
							rid = bufs_[nb.second];
							break;
						}
					}
				}
				if (rid.index == 0) {
					d_.free_rid(s.params);
					err_ = std::string("vec rd: ") + dd.kernel + ": unbound '" + bd.name + "'";
					return false;
				}
				rb.push_back({ bd.binding, bd.type, rid });
			}
			s.set = d_.uniform_set(k.shader, rb);
			if (s.set.index == 0) {
				d_.free_rid(s.params);
				err_ = std::string("vec rd: uniform_set for ") + dd.kernel + ": " + d_.error();
				return false;
			}
			it = sites_.emplace(skey, s).first;
		} else if (it->second.words != words) {
			if (!d_.buffer_update(it->second.params, 0, words.size() * 4, words.data())) {
				err_ = std::string("vec rd: params update for ") + dd.kernel + ": " + d_.error();
				return false;
			}
			it->second.words = words;
		}
		recs.push_back({ &k, it->second.set, dd.groups });
	}
	// Pass 2: one compute list, a barrier between dispatches, one submit.
	if (!d_.list_begin()) {
		err_ = "vec rd: list_begin: " + d_.error();
		return false;
	}
	for (size_t i = 0; i < recs.size(); ++i) {
		if (recs[i].groups == 0) {
			continue;
		}
		d_.bind_pipeline(recs[i].k->pipeline);
		d_.bind_uniform_set(recs[i].set);
		d_.dispatch(recs[i].groups);
		++dispatches_;
		if (i + 1 < recs.size()) {
			d_.barrier();
		}
	}
	d_.list_end();
	d_.submit();
	pending_ = true;
	++phases_;
	return true;
}
