// SPDX-License-Identifier: Apache-2.0 OR MIT
#include "avbd_rd.h"

#include <cstring>

#include "avbd_topology.h"

// Generated by kernels/avbd/gen.sh into the build directory: one byte array
// per SPIR-V kernel plus find(name).
#include "avbd_kernels.inc"

namespace {

// The forward and dual kernels this backend dispatches. The self-collision
// scan and the backward pass are in the table and the embedded SPIR-V too;
// they are wired in the next cut, after the fixture passes on this one.
const char *const kForwardKernels[] = {
	"vbd_init", "spring_force", "vbd_gather_spring", "attachment_force_al", "vbd_gather_attachment",
	"triangle_membrane_force_al", "vbd_gather_triangle", "triangle_bending_force_al",
	"vbd_gather_bending", "vbd_solve_apply", "attachment_dual_update",
	"triangle_membrane_dual_update", "triangle_bending_dual_update",
};

const cloth::avbd_table::KernelDesc *table_find(const char *name) {
	for (uint32_t i = 0; i < cloth::avbd_table::kNumKernels; ++i) {
		if (std::strcmp(cloth::avbd_table::kKernels[i].name, name) == 0) {
			return &cloth::avbd_table::kKernels[i];
		}
	}
	return nullptr;
}

// float3 in a StructuredBuffer has a 16-byte stride, so host-side tight xyz
// triples are expanded on upload and compacted on readback. Same convention as
// the Vulkan and Metal backends.
std::vector<float> pad_v3(const float *xyz, uint32_t n) {
	std::vector<float> out(size_t(4) * n, 0.0f);
	for (uint32_t i = 0; i < n; ++i) {
		out[4 * i + 0] = xyz[3 * i + 0];
		out[4 * i + 1] = xyz[3 * i + 1];
		out[4 * i + 2] = xyz[3 * i + 2];
	}
	return out;
}

} // namespace

AvbdRd::AvbdRd(rdc::Device &dev) :
		d_(dev) {
	ok_ = load_kernels();
}

AvbdRd::~AvbdRd() {
	// Buffers own the uniform sets (Godot frees dependents); pipelines and
	// shaders are freed explicitly. The device outlives us.
	if (pending_) {
		sync();
	}
	Buf *all[] = { &positions_, &predicted_, &mass_, &gScratch_, &hScratch_, &vertPerm_b_,
		&sp_p1_, &sp_p2_, &sp_rest_, &sp_k_, &sp_gradA_, &sp_hess_, &sp_off_, &sp_idx_, &sp_role_,
		&at_vert_, &at_fixed_, &at_k_, &at_lambda_, &at_gamma_, &at_gradV_, &at_hess_, &at_off_, &at_idx_,
		&tri_idx_, &tri_k_, &tri_l0_, &tri_l1_, &tri_gamma_, &tri_grad_, &tri_hess_, &tri_invuv_, &tri_off_,
		&tri_idxc_, &tri_role_, &bd_idx_, &bd_w_, &bd_n_, &bd_k_, &bd_lambda_, &bd_gamma_, &bd_grad_, &bd_hess_,
		&bd_off_, &bd_idxc_, &bd_role_, &dualAttachParams_, &dualTriParams_, &dualBendParams_ };
	for (Buf *b : all) {
		free_buf(*b);
	}
	for (Buf &b : initParams_) {
		free_buf(b);
	}
	for (Buf &b : colorParams_) {
		free_buf(b);
	}
	for (auto &kv : kernels_) {
		d_.free_rid(kv.second.pipeline);
		d_.free_rid(kv.second.shader);
	}
}

bool AvbdRd::load_kernels() {
	if (!d_.ok()) {
		err_ = "no RenderingDevice";
		return false;
	}
	for (const char *name : kForwardKernels) {
		const cloth::avbd_table::KernelDesc *desc = table_find(name);
		const avbd_kernels::Entry *bytes = avbd_kernels::find(name);
		if (desc == nullptr || bytes == nullptr) {
			err_ = std::string("kernel missing from table or embed: ") + name;
			return false;
		}
		Kernel k;
		k.desc = desc;
		k.shader = d_.shader_from_spirv(bytes->bytes, bytes->size);
		if (k.shader.index == 0) {
			err_ = std::string(name) + ": " + d_.error();
			return false;
		}
		k.pipeline = d_.compute_pipeline(k.shader);
		if (k.pipeline.index == 0) {
			err_ = std::string(name) + ": " + d_.error();
			return false;
		}
		kernels_[name] = k;
	}
	return true;
}

// --- buffers ----------------------------------------------------------------

AvbdRd::Buf AvbdRd::make_f32(const std::vector<float> &v) {
	Buf b;
	if (v.empty()) {
		return b;
	}
	b.bytes = v.size() * sizeof(float);
	b.rid = d_.storage_buffer(b.bytes, v.data());
	return b;
}

AvbdRd::Buf AvbdRd::make_u32(const std::vector<uint32_t> &v) {
	Buf b;
	if (v.empty()) {
		return b;
	}
	b.bytes = v.size() * sizeof(uint32_t);
	b.rid = d_.storage_buffer(b.bytes, v.data());
	return b;
}

AvbdRd::Buf AvbdRd::make_v3(const float *xyz, uint32_t n) {
	return make_f32(pad_v3(xyz, n));
}

AvbdRd::Buf AvbdRd::make_zero(size_t bytes) {
	Buf b;
	if (bytes == 0) {
		return b;
	}
	b.bytes = bytes;
	b.rid = d_.storage_buffer(bytes, nullptr);
	return b;
}

void AvbdRd::update_v3(Buf &b, const float *xyz, uint32_t n) {
	if (!b.valid()) {
		return;
	}
	if (pending_) {
		sync();
	}
	const std::vector<float> p = pad_v3(xyz, n);
	d_.buffer_update(b.rid, 0, p.size() * sizeof(float), p.data());
}

void AvbdRd::update_f32(Buf &b, const std::vector<float> &v) {
	if (!b.valid() || v.empty()) {
		return;
	}
	if (pending_) {
		sync();
	}
	d_.buffer_update(b.rid, 0, v.size() * sizeof(float), v.data());
}

void AvbdRd::free_buf(Buf &b) {
	if (b.valid()) {
		d_.free_rid(b.rid);
	}
	b = Buf();
}

void AvbdRd::invalidate_sets() {
	// Sets are owned by their buffers on the Godot side (freed with them);
	// the cache only forgets them here.
	sets_.clear();
}

// --- uploads ----------------------------------------------------------------

void AvbdRd::setupMesh(uint32_t nVerts, const float *positions, const float *predicted,
		const float *mass, float invHSquared) {
	if (pending_) {
		sync();
	}
	nVerts_ = nVerts;
	invHSq_ = invHSquared;
	free_buf(positions_);
	free_buf(predicted_);
	free_buf(mass_);
	free_buf(gScratch_);
	free_buf(hScratch_);
	free_buf(vertPerm_b_);
	positions_ = make_v3(positions, nVerts);
	predicted_ = make_v3(predicted, nVerts);
	mass_ = make_f32(std::vector<float>(mass, mass + nVerts));
	gScratch_ = make_zero(size_t(16) * nVerts);
	hScratch_ = make_zero(size_t(24) * nVerts);
	vertPerm_.resize(nVerts);
	for (uint32_t i = 0; i < nVerts; ++i) {
		vertPerm_[i] = i;
	}
	vertPerm_b_ = make_u32(vertPerm_);
	colorOffsets_ = { 0u, nVerts };
	meshReady_ = positions_.valid() && predicted_.valid() && mass_.valid() && gScratch_.valid() &&
			hScratch_.valid() && vertPerm_b_.valid();
	paramsReady_ = false;
	invalidate_sets();
}

void AvbdRd::uploadSprings(uint32_t nSprings, const uint32_t *p1Idx, const uint32_t *p2Idx,
		const float *restLen, const float *stiffness) {
	if (pending_) {
		sync();
	}
	nSprings_ = nSprings;
	springP1_.assign(p1Idx, p1Idx + nSprings);
	springP2_.assign(p2Idx, p2Idx + nSprings);
	Buf *old[] = { &sp_p1_, &sp_p2_, &sp_rest_, &sp_k_, &sp_gradA_, &sp_hess_, &sp_off_, &sp_idx_, &sp_role_ };
	for (Buf *b : old) {
		free_buf(*b);
	}
	if (nSprings == 0) {
		invalidate_sets();
		return;
	}
	sp_p1_ = make_u32(springP1_);
	sp_p2_ = make_u32(springP2_);
	sp_rest_ = make_f32(std::vector<float>(restLen, restLen + nSprings));
	sp_k_ = make_f32(std::vector<float>(stiffness, stiffness + nSprings));
	sp_gradA_ = make_zero(size_t(16) * nSprings);
	sp_hess_ = make_zero(size_t(24) * nSprings);
	std::vector<uint32_t> ends(2 * nSprings);
	for (uint32_t i = 0; i < nSprings; ++i) {
		ends[2 * i] = p1Idx[i];
		ends[2 * i + 1] = p2Idx[i];
	}
	std::vector<uint32_t> off, idx, role;
	avbd::build_csr(nVerts_, nSprings, 2, ends.data(), off, idx, role);
	sp_off_ = make_u32(off);
	sp_idx_ = make_u32(idx);
	sp_role_ = make_u32(role);
	invalidate_sets();
}

void AvbdRd::uploadAttachments(uint32_t nAttach, const uint32_t *vertIdx,
		const float *fixedPos, const float *stiffness) {
	if (pending_) {
		sync();
	}
	nAttach_ = nAttach;
	Buf *old[] = { &at_vert_, &at_fixed_, &at_k_, &at_lambda_, &at_gamma_, &at_gradV_, &at_hess_, &at_off_, &at_idx_ };
	for (Buf *b : old) {
		free_buf(*b);
	}
	paramsReady_ = false; // the dual params carry the count
	if (nAttach == 0) {
		attachGamma_.clear();
		invalidate_sets();
		return;
	}
	at_vert_ = make_u32(std::vector<uint32_t>(vertIdx, vertIdx + nAttach));
	at_fixed_ = make_v3(fixedPos, nAttach);
	at_k_ = make_f32(std::vector<float>(stiffness, stiffness + nAttach));
	attachGamma_.assign(stiffness, stiffness + nAttach);
	for (float &g : attachGamma_) {
		g *= gammaScale_;
	}
	at_gamma_ = make_f32(attachGamma_);
	at_lambda_ = make_zero(size_t(16) * nAttach);
	at_gradV_ = make_zero(size_t(16) * nAttach);
	at_hess_ = make_zero(size_t(4) * nAttach);
	std::vector<uint32_t> off, idx, roleUnused;
	avbd::build_csr(nVerts_, nAttach, 1, vertIdx, off, idx, roleUnused);
	at_off_ = make_u32(off);
	at_idx_ = make_u32(idx);
	invalidate_sets();
}

void AvbdRd::uploadTriangles(uint32_t nTri, const uint32_t *triIdx, const float *invUV,
		const float *stiffness) {
	if (pending_) {
		sync();
	}
	nTri_ = nTri;
	triIdx_.assign(triIdx, triIdx + 3 * nTri);
	Buf *old[] = { &tri_idx_, &tri_k_, &tri_l0_, &tri_l1_, &tri_gamma_, &tri_grad_, &tri_hess_, &tri_invuv_,
		&tri_off_, &tri_idxc_, &tri_role_ };
	for (Buf *b : old) {
		free_buf(*b);
	}
	paramsReady_ = false;
	if (nTri == 0) {
		triGamma_.clear();
		invalidate_sets();
		return;
	}
	tri_idx_ = make_u32(triIdx_);
	tri_k_ = make_f32(std::vector<float>(stiffness, stiffness + nTri));
	triGamma_.assign(stiffness, stiffness + nTri);
	for (float &g : triGamma_) {
		g *= gammaScale_;
	}
	tri_gamma_ = make_f32(triGamma_);
	tri_l0_ = make_zero(size_t(16) * nTri);
	tri_l1_ = make_zero(size_t(16) * nTri);
	tri_grad_ = make_zero(size_t(16) * 3 * nTri);
	tri_hess_ = make_zero(size_t(4) * 3 * nTri);
	tri_invuv_ = make_f32(std::vector<float>(invUV, invUV + 4 * nTri));
	std::vector<uint32_t> off, idx, role;
	avbd::build_csr(nVerts_, nTri, 3, triIdx, off, idx, role);
	tri_off_ = make_u32(off);
	tri_idxc_ = make_u32(idx);
	tri_role_ = make_u32(role);
	invalidate_sets();
}

void AvbdRd::uploadBendings(uint32_t nBend, const uint32_t *bendIdx, const float *weight,
		const float *nTarget, const float *stiffness) {
	if (pending_) {
		sync();
	}
	nBend_ = nBend;
	bendIdx_.assign(bendIdx, bendIdx + 4 * nBend);
	Buf *old[] = { &bd_idx_, &bd_w_, &bd_n_, &bd_k_, &bd_lambda_, &bd_gamma_, &bd_grad_, &bd_hess_, &bd_off_,
		&bd_idxc_, &bd_role_ };
	for (Buf *b : old) {
		free_buf(*b);
	}
	paramsReady_ = false;
	if (nBend == 0) {
		bendGamma_.clear();
		invalidate_sets();
		return;
	}
	bd_idx_ = make_u32(bendIdx_);
	bd_w_ = make_f32(std::vector<float>(weight, weight + 4 * nBend));
	bd_n_ = make_f32(std::vector<float>(nTarget, nTarget + nBend));
	bd_k_ = make_f32(std::vector<float>(stiffness, stiffness + nBend));
	bendGamma_.assign(stiffness, stiffness + nBend);
	for (float &g : bendGamma_) {
		g *= gammaScale_;
	}
	bd_gamma_ = make_f32(bendGamma_);
	bd_lambda_ = make_zero(size_t(16) * nBend);
	bd_grad_ = make_zero(size_t(16) * 4 * nBend);
	bd_hess_ = make_zero(size_t(4) * 4 * nBend);
	std::vector<uint32_t> off, idx, role;
	avbd::build_csr(nVerts_, nBend, 4, bendIdx, off, idx, role);
	bd_off_ = make_u32(off);
	bd_idxc_ = make_u32(idx);
	bd_role_ = make_u32(role);
	invalidate_sets();
}

void AvbdRd::buildColoring() {
	if (!meshReady_) {
		return;
	}
	if (pending_) {
		sync();
	}
	avbd::greedy_coloring(nVerts_, nSprings_, springP1_.data(), springP2_.data(), nTri_, triIdx_.data(),
			nBend_, bendIdx_.data(), vertPerm_, colorOffsets_);
	d_.buffer_update(vertPerm_b_.rid, 0, vertPerm_.size() * sizeof(uint32_t), vertPerm_.data());
	paramsReady_ = false;
	invalidate_sets();
}

void AvbdRd::setGammaScale(float scale) {
	gammaScale_ *= scale;
	for (float &g : attachGamma_) {
		g *= scale;
	}
	for (float &g : triGamma_) {
		g *= scale;
	}
	for (float &g : bendGamma_) {
		g *= scale;
	}
	update_f32(at_gamma_, attachGamma_);
	update_f32(tri_gamma_, triGamma_);
	update_f32(bd_gamma_, bendGamma_);
}

void AvbdRd::setPenaltyRamp(float beta, float penaltyMax) {
	beta_ = beta;
	penaltyMax_ = penaltyMax;
	paramsReady_ = false;
}

void AvbdRd::updateState(const float *positions, const float *predicted) {
	update_v3(positions_, positions, nVerts_);
	update_v3(predicted_, predicted, nVerts_);
}

void AvbdRd::updateAttachmentFixedPos(const float *fixedPos) {
	if (nAttach_ == 0) {
		return;
	}
	update_v3(at_fixed_, fixedPos, nAttach_);
}

// --- params and uniform sets ------------------------------------------------

void AvbdRd::ensure_params() {
	if (paramsReady_) {
		return;
	}
	if (pending_) {
		sync();
	}
	for (Buf &b : initParams_) {
		free_buf(b);
	}
	for (Buf &b : colorParams_) {
		free_buf(b);
	}
	free_buf(dualAttachParams_);
	free_buf(dualTriParams_);
	free_buf(dualBendParams_);
	const uint32_t nc = numColors();
	initParams_.assign(nc, Buf());
	colorParams_.assign(nc, Buf());
	for (uint32_t c = 0; c < nc; ++c) {
		const uint32_t offset = colorOffsets_[c];
		const uint32_t count = colorOffsets_[c + 1] - offset;
		// {float invHSquared; uint colorOffset; uint count;} padded to 16.
		struct {
			float invHSq;
			uint32_t offset, count, pad;
		} ip{ invHSq_, offset, count, 0u };
		initParams_[c].bytes = sizeof ip;
		initParams_[c].rid = d_.uniform_buffer(sizeof ip, &ip);
		// {uint colorOffset; uint count;} -- gathers and solve_apply share it.
		uint32_t gp[4] = { offset, count, 0u, 0u };
		colorParams_[c].bytes = sizeof gp;
		colorParams_[c].rid = d_.uniform_buffer(sizeof gp, gp);
	}
	// {float beta; float penaltyMax; uint count;} per family.
	struct DualP {
		float beta, penaltyMax;
		uint32_t count, pad;
	};
	if (nAttach_) {
		DualP p{ beta_, penaltyMax_, nAttach_, 0u };
		dualAttachParams_.bytes = sizeof p;
		dualAttachParams_.rid = d_.uniform_buffer(sizeof p, &p);
	}
	if (nTri_) {
		DualP p{ beta_, penaltyMax_, nTri_, 0u };
		dualTriParams_.bytes = sizeof p;
		dualTriParams_.rid = d_.uniform_buffer(sizeof p, &p);
	}
	if (nBend_) {
		DualP p{ beta_, penaltyMax_, nBend_, 0u };
		dualBendParams_.bytes = sizeof p;
		dualBendParams_.rid = d_.uniform_buffer(sizeof p, &p);
	}
	paramsReady_ = true;
	invalidate_sets();
}

::RID AvbdRd::set_for(const char *kernel, int color, const Binds &binds) {
	const std::string key = std::string(kernel) + "#" + std::to_string(color);
	auto it = sets_.find(key);
	if (it != sets_.end()) {
		return it->second;
	}
	const Kernel &k = kernels_[kernel];
	std::vector<rdc::Binding> rb;
	rb.reserve(k.desc->nBindings);
	for (uint32_t b = 0; b < k.desc->nBindings; ++b) {
		const cloth::avbd_table::BindingDesc &bd = k.desc->bindings[b];
		::RID rid;
		if (int32_t(bd.binding) == k.desc->paramsBinding) {
			if (std::strcmp(kernel, "vbd_init") == 0) {
				rid = initParams_[color].rid;
			} else if (std::strcmp(kernel, "attachment_dual_update") == 0) {
				rid = dualAttachParams_.rid;
			} else if (std::strcmp(kernel, "triangle_membrane_dual_update") == 0) {
				rid = dualTriParams_.rid;
			} else if (std::strcmp(kernel, "triangle_bending_dual_update") == 0) {
				rid = dualBendParams_.rid;
			} else {
				rid = colorParams_[color].rid;
			}
		} else {
			for (const auto &nb : binds) {
				if (std::strcmp(nb.first, bd.name) == 0) {
					rid = nb.second->rid;
					break;
				}
			}
		}
		if (rid.index == 0) {
			err_ = std::string(kernel) + ": unbound '" + bd.name + "'";
			return ::RID();
		}
		rb.push_back({ bd.binding, bd.type, rid });
	}
	::RID set = d_.uniform_set(k.shader, rb);
	if (set.index == 0) {
		err_ = std::string(kernel) + ": " + d_.error();
		return set;
	}
	sets_[key] = set;
	return set;
}

bool AvbdRd::dispatch(const char *kernel, int color, uint32_t threads, const Binds &binds) {
	if (threads == 0) {
		return true;
	}
	::RID set = set_for(kernel, color, binds);
	if (set.index == 0) {
		return false;
	}
	d_.bind_pipeline(kernels_[kernel].pipeline);
	d_.bind_uniform_set(set);
	d_.dispatch(rdc::Device::groups_for(threads, kernels_[kernel].desc->threadgroup[0]));
	return true;
}

// --- recording --------------------------------------------------------------

void AvbdRd::record_iteration() {
	const uint32_t nc = numColors();
	for (uint32_t k = 0; k < nc; ++k) {
		const uint32_t count = colorOffsets_[k + 1] - colorOffsets_[k];
		if (count == 0) {
			continue;
		}
		const int c = int(k);
		// init writes this colour's scratch rows; the force kernels read
		// positions only and write disjoint per-constraint buffers -- no
		// barrier among these five.
		dispatch("vbd_init", c, count,
				{ { "positions", &positions_ }, { "predicted", &predicted_ }, { "mass", &mass_ },
						{ "gScratch", &gScratch_ }, { "hScratch", &hScratch_ }, { "vertPerm", &vertPerm_b_ } });
		if (nSprings_) {
			dispatch("spring_force", -1, nSprings_,
					{ { "positions", &positions_ }, { "p1Idx", &sp_p1_ }, { "p2Idx", &sp_p2_ },
							{ "restLen", &sp_rest_ }, { "stiffness", &sp_k_ }, { "gradA", &sp_gradA_ },
							{ "hess", &sp_hess_ } });
		}
		if (nAttach_) {
			dispatch("attachment_force_al", -1, nAttach_,
					{ { "positions", &positions_ }, { "vertIdx", &at_vert_ }, { "fixedPos", &at_fixed_ },
							{ "stiffness", &at_k_ }, { "lambda", &at_lambda_ }, { "gradV", &at_gradV_ },
							{ "hessScalar", &at_hess_ } });
		}
		if (nTri_) {
			dispatch("triangle_membrane_force_al", -1, nTri_,
					{ { "positions", &positions_ }, { "idx", &tri_idx_ }, { "stiffness", &tri_k_ },
							{ "lambda0", &tri_l0_ }, { "lambda1", &tri_l1_ }, { "grad", &tri_grad_ },
							{ "hessScalar", &tri_hess_ }, { "inv_deltaUV", &tri_invuv_ } });
		}
		if (nBend_) {
			dispatch("triangle_bending_force_al", -1, nBend_,
					{ { "positions", &positions_ }, { "idx", &bd_idx_ }, { "weight", &bd_w_ },
							{ "nTarget", &bd_n_ }, { "stiffness", &bd_k_ }, { "lambda", &bd_lambda_ },
							{ "grad", &bd_grad_ }, { "hessScalar", &bd_hess_ } });
		}
		d_.barrier();
		// The gathers all accumulate into gScratch/hScratch: serialise them.
		if (nSprings_) {
			dispatch("vbd_gather_spring", c, count,
					{ { "springGradA", &sp_gradA_ }, { "springHess", &sp_hess_ }, { "vertSpringOffset", &sp_off_ },
							{ "vertSpringIdx", &sp_idx_ }, { "vertSpringRole", &sp_role_ }, { "gScratch", &gScratch_ },
							{ "hScratch", &hScratch_ }, { "vertPerm", &vertPerm_b_ } });
			d_.barrier();
		}
		if (nAttach_) {
			dispatch("vbd_gather_attachment", c, count,
					{ { "attachGradV", &at_gradV_ }, { "attachHessScalar", &at_hess_ },
							{ "vertAttachOffset", &at_off_ }, { "vertAttachIdx", &at_idx_ }, { "gScratch", &gScratch_ },
							{ "hScratch", &hScratch_ }, { "vertPerm", &vertPerm_b_ } });
			d_.barrier();
		}
		if (nTri_) {
			dispatch("vbd_gather_triangle", c, count,
					{ { "triGrad", &tri_grad_ }, { "triHessScalar", &tri_hess_ }, { "vertTriOffset", &tri_off_ },
							{ "vertTriIdx", &tri_idxc_ }, { "vertTriRole", &tri_role_ }, { "gScratch", &gScratch_ },
							{ "hScratch", &hScratch_ }, { "vertPerm", &vertPerm_b_ } });
			d_.barrier();
		}
		if (nBend_) {
			dispatch("vbd_gather_bending", c, count,
					{ { "bendGrad", &bd_grad_ }, { "bendHessScalar", &bd_hess_ }, { "vertBendOffset", &bd_off_ },
							{ "vertBendIdx", &bd_idxc_ }, { "vertBendRole", &bd_role_ }, { "gScratch", &gScratch_ },
							{ "hScratch", &hScratch_ }, { "vertPerm", &vertPerm_b_ } });
			d_.barrier();
		}
		dispatch("vbd_solve_apply", c, count,
				{ { "gScratch", &gScratch_ }, { "hScratch", &hScratch_ }, { "positions", &positions_ },
						{ "vertPerm", &vertPerm_b_ } });
		d_.barrier(); // the next colour's init and forces read positions
	}
}

void AvbdRd::record_duals() {
	if (nAttach_) {
		dispatch("attachment_dual_update", -1, nAttach_,
				{ { "positions", &positions_ }, { "vertIdx", &at_vert_ }, { "fixedPos", &at_fixed_ },
						{ "gamma", &at_gamma_ }, { "lambda", &at_lambda_ } });
	}
	if (nTri_) {
		dispatch("triangle_membrane_dual_update", -1, nTri_,
				{ { "positions", &positions_ }, { "idx", &tri_idx_ }, { "gamma", &tri_gamma_ },
						{ "lambda0", &tri_l0_ }, { "lambda1", &tri_l1_ }, { "inv_deltaUV", &tri_invuv_ } });
	}
	if (nBend_) {
		dispatch("triangle_bending_dual_update", -1, nBend_,
				{ { "positions", &positions_ }, { "idx", &bd_idx_ }, { "weight", &bd_w_ }, { "nTarget", &bd_n_ },
						{ "gamma", &bd_gamma_ }, { "lambda", &bd_lambda_ } });
	}
	// Three disjoint lambda families; one barrier before the next iteration's
	// force kernels read them.
	d_.barrier();
}

bool AvbdRd::begin_record() {
	if (!ok_ || !meshReady_) {
		return false;
	}
	ensure_params();
	if (pending_) {
		sync();
	}
	err_.clear();
	d_.list_begin();
	return true;
}

void AvbdRd::end_record_and_submit() {
	d_.list_end();
	d_.submit();
	pending_ = true;
}

int AvbdRd::step() {
	if (!begin_record()) {
		return -1;
	}
	record_iteration();
	end_record_and_submit();
	return err_.empty() ? 0 : -1;
}

int AvbdRd::stepDualAttachments() {
	if (nAttach_ == 0) {
		return meshReady_ ? 0 : -1;
	}
	if (!begin_record()) {
		return -1;
	}
	dispatch("attachment_dual_update", -1, nAttach_,
			{ { "positions", &positions_ }, { "vertIdx", &at_vert_ }, { "fixedPos", &at_fixed_ },
					{ "gamma", &at_gamma_ }, { "lambda", &at_lambda_ } });
	end_record_and_submit();
	return err_.empty() ? 0 : -1;
}

int AvbdRd::stepDualMembrane() {
	if (nTri_ == 0) {
		return meshReady_ ? 0 : -1;
	}
	if (!begin_record()) {
		return -1;
	}
	dispatch("triangle_membrane_dual_update", -1, nTri_,
			{ { "positions", &positions_ }, { "idx", &tri_idx_ }, { "gamma", &tri_gamma_ },
					{ "lambda0", &tri_l0_ }, { "lambda1", &tri_l1_ }, { "inv_deltaUV", &tri_invuv_ } });
	end_record_and_submit();
	return err_.empty() ? 0 : -1;
}

int AvbdRd::stepDualBending() {
	if (nBend_ == 0) {
		return meshReady_ ? 0 : -1;
	}
	if (!begin_record()) {
		return -1;
	}
	dispatch("triangle_bending_dual_update", -1, nBend_,
			{ { "positions", &positions_ }, { "idx", &bd_idx_ }, { "weight", &bd_w_ }, { "nTarget", &bd_n_ },
					{ "gamma", &bd_gamma_ }, { "lambda", &bd_lambda_ } });
	end_record_and_submit();
	return err_.empty() ? 0 : -1;
}

int AvbdRd::run(int iters, bool duals) {
	if (iters < 1) {
		return meshReady_ ? 0 : -1;
	}
	if (!begin_record()) {
		return -1;
	}
	for (int it = 0; it < iters; ++it) {
		record_iteration();
		if (duals) {
			record_duals();
		}
	}
	end_record_and_submit();
	return err_.empty() ? 0 : -1;
}

void AvbdRd::sync() {
	if (!pending_) {
		return;
	}
	d_.sync();
	pending_ = false;
}

void AvbdRd::readPositions(std::vector<float> &out) {
	out.clear();
	if (!meshReady_) {
		return;
	}
	if (pending_) {
		sync();
	}
	const std::vector<uint8_t> bytes = d_.buffer_get(positions_.rid);
	if (bytes.size() < size_t(16) * nVerts_) {
		return;
	}
	out.resize(size_t(3) * nVerts_);
	const float *f = reinterpret_cast<const float *>(bytes.data());
	for (uint32_t i = 0; i < nVerts_; ++i) {
		out[3 * i + 0] = f[4 * i + 0];
		out[3 * i + 1] = f[4 * i + 1];
		out[3 * i + 2] = f[4 * i + 2];
	}
}
