#!/usr/bin/env python3
"""Write the host harness's kernel runners from kernels/ggml/kernels.txt.

Each kernel's slangc cpp emit (kernels/ggml/cpp/<k>_emit.cpp) is included in
a namespace of its own, and run_kernel(id, ...) dispatches kernel `id` (its
line in kernels.txt, as in GgmlKernelTable.inc) over a grid, with the params
words bound at set 1 base 0 and every storage binding (s0, s1, s2, dst) over
the one memory block that stands in for the RD buffer.

A kernel with no cpp emit (it shares group memory: kernels/ggml/gen.sh
skips it) runs as its kernels/ggml/cpp_siblings.txt sibling when it has one
(same thread group, same grid), else as its `<k>_serial` sibling when that
runs one thread per group over the same grid (one work group per row: the
NORM/RMS_NORM/MEAN/SOFT_MAX siblings). Any other kernel with no emit gets no
runner (run_kernel returns false): its packer picks its `<k>_serial` sibling
itself under GGML_RD_SERIAL=1, which the harness sets (FLASH_ATTN_EXT, whose
sibling has its own grid).

    python gen_host_kernels.py kernels/ggml/kernels.txt <out.cpp> [kernels/ggml/cpp_siblings.txt]
"""
import os
import re
import sys


def main():
    kernels = [l.strip() for l in open(sys.argv[1]) if l.strip() and not l.startswith('#')]
    here = os.path.dirname(os.path.abspath(sys.argv[1]))
    cpp_dir = os.path.join(here, 'cpp')
    has_cpp = {k: os.path.exists(os.path.join(cpp_dir, k + '_emit.cpp')) for k in kernels}
    sibling = {}
    if len(sys.argv) > 3:
        for l in open(sys.argv[3]):
            words = l.split('#', 1)[0].split()
            if len(words) == 2:
                sibling[words[0]] = words[1]
    for k, s in sibling.items():
        if k not in kernels or s not in kernels or s in sibling:
            sys.exit('cpp_siblings: %s -> %s is not a pair of kernels.txt kernels' % (k, s))

    def one_thread(k):
        src = open(os.path.join(here, 'slang', k + '.slang')).read()
        return re.search(r'numthreads\(\s*1\s*,\s*1\s*,\s*1\s*\)', src) is not None

    runs = {}  # kernel -> the emit that runs for it (absent: no runner)
    for k in kernels:
        if k in sibling:
            runs[k] = sibling[k]
        elif has_cpp[k]:
            runs[k] = k
        elif has_cpp.get(k + '_serial', False):
            if one_thread(k + '_serial'):
                runs[k] = k + '_serial'
        else:
            sys.exit('error: %s has no cpp emit and no sibling with one' % k)
    w = []
    w.append('// GENERATED by tests/ggml_rd_kernels/gen_host_kernels.py from kernels/ggml/kernels.txt.')
    w.append('#include <cstddef>')
    w.append('#include <cstdint>')
    w.append('#include <type_traits>')
    w.append('')
    w.append('// An index past a binding reads (and writes) element 0 instead of leaving')
    w.append('// the memory block, so a wrong stride fails a case and does not crash the')
    w.append('// harness: the swapped-stride control sends a row kernel gigabytes past it.')
    w.append('#ifndef SLANG_ENABLE_BOUND_ZERO_INDEX')
    w.append('#define SLANG_ENABLE_BOUND_ZERO_INDEX')
    w.append('#endif')
    w.append('// The prelude once, at global scope; every emit then skips its own copy')
    w.append('// (include guard) and they all share these types.')
    w.append('#include "slang-cpp-prelude.h"')
    w.append('#undef SLANG_PRELUDE_EXTERN_C')
    w.append('#undef SLANG_PRELUDE_EXTERN_C_START')
    w.append('#undef SLANG_PRELUDE_EXTERN_C_END')
    w.append('#define SLANG_PRELUDE_EXTERN_C')
    w.append('#define SLANG_PRELUDE_EXTERN_C_START')
    w.append('#define SLANG_PRELUDE_EXTERN_C_END')
    w.append('')
    for k in (k for k in kernels if has_cpp[k]):
        w.append('namespace k_%s {' % k)
        w.append('#include "%s_emit.cpp"' % k)
        w.append('}')
    w.append('')
    w.append('namespace {')
    w.append('template <class B>')
    w.append('void bind(B &b, void *p, size_t bytes) {')
    w.append('\tusing T = std::remove_reference_t<decltype(*b.data)>;')
    w.append('\tb.data = static_cast<T *>(p);')
    w.append('\tb.count = bytes / sizeof(T);')
    w.append('}')
    w.append('template <class GP, class SLOT>')
    w.append('void run(void (*fn)(ComputeVaryingInput *, void *, void *), uint32_t *words, void *mem, size_t bytes,')
    w.append('\t\tconst uint32_t g[3]) {')
    w.append('\tGP gp{};')
    w.append('\tbind(gp.params_0, words, 64 * 4);')
    w.append('\tbind(gp.s0_0, mem, bytes);')
    w.append('\tbind(gp.s1_0, mem, bytes);')
    w.append('\tbind(gp.s2_0, mem, bytes);')
    w.append('\tbind(gp.dst_0, mem, bytes);')
    w.append('\tSLOT slot{};')
    w.append('\tslot.base_0 = 0;')
    w.append('\tgp.slot_0 = &slot;')
    w.append('\tComputeVaryingInput vi{};')
    w.append('\tvi.startGroupID = uint3(0u, 0u, 0u);')
    w.append('\tvi.endGroupID = uint3(g[0], g[1], g[2]);')
    w.append('\tfn(&vi, nullptr, &gp);')
    w.append('}')
    w.append('} // namespace')
    w.append('')
    w.append('bool run_kernel(int id, uint32_t *words, void *mem, size_t bytes, const uint32_t groups[3]) {')
    w.append('\tswitch (id) {')
    for i, k in enumerate(kernels):
        if k not in runs:
            continue
        r = runs[k]
        w.append('\t\tcase %d:%s' % (i, '' if r == k else ' // %s runs as %s' % (k, r)))
        w.append('\t\t\trun<k_%s::GlobalParams_0, k_%s::Slot_0>(&k_%s::main_0, words, mem, bytes, groups);' % (r, r, r))
        w.append('\t\t\treturn true;')
    w.append('\t\tdefault:')
    w.append('\t\t\treturn false;')
    w.append('\t}')
    w.append('}')
    w.append('')
    open(sys.argv[2], 'w', newline='\n').write('\n'.join(w))
    print('wrote %s: %d kernels, %d with a host runner (%d by a sibling)' % (sys.argv[2], len(kernels), len(runs),
          sum(1 for k, r in runs.items() if r != k)))


if __name__ == '__main__':
    main()
