#!/usr/bin/env python3
"""Embed SPIR-V kernels into the guest as byte arrays.

The guest has no filesystem, so the kernels ship inside the ELF. This writes a
header with one `static const uint8_t` array per .spv plus a name -> bytes
table, so a backend can look a kernel up by the same name the binding table
uses. Precedent: modules/cassie/spv_to_header.py.

    python kernels/embed_spv.py kernels/avbd guest/avbd_kernels.inc
    python kernels/embed_spv.py --namespace ggml_kernels build/spv-ggml build/ggml_kernels.inc

--namespace names the C++ namespace (default avbd_kernels), so two stages'
tables can be included in one translation unit.
"""

import argparse
import pathlib


def ident(name):
    return "".join(c if c.isalnum() else "_" for c in name)


def emit(src_dir, out_path, namespace="avbd_kernels"):
    src_dir = pathlib.Path(src_dir)
    files = sorted(src_dir.glob("*.spv"))
    if not files:
        raise SystemExit("no .spv under %s" % src_dir)
    lines = [
        "// Generated by kernels/embed_spv.py from %s. Do not edit; regenerate." % src_dir.as_posix(),
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace %s {" % namespace,
        "",
    ]
    for f in files:
        data = f.read_bytes()
        if len(data) % 4 != 0 or data[:4] != b"\x03\x02\x23\x07":
            raise SystemExit("%s is not little-endian SPIR-V" % f)
        lines.append("static const uint8_t k_%s[%d] = {" % (ident(f.stem), len(data)))
        for i in range(0, len(data), 24):
            chunk = data[i:i + 24]
            lines.append("\t" + ",".join("0x%02x" % b for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("struct Entry {")
    lines.append("\tconst char *name;")
    lines.append("\tconst uint8_t *bytes;")
    lines.append("\tsize_t size;")
    lines.append("};")
    lines.append("")
    lines.append("static const Entry kEntries[] = {")
    for f in files:
        lines.append('\t{ "%s", k_%s, sizeof(k_%s) },' % (f.stem, ident(f.stem), ident(f.stem)))
    lines.append("};")
    lines.append("static const size_t kCount = sizeof(kEntries) / sizeof(kEntries[0]);")
    lines.append("")
    lines.append("inline const Entry *find(const char *name) {")
    lines.append("\tfor (size_t i = 0; i < kCount; ++i) {")
    lines.append("\t\tconst char *a = kEntries[i].name;")
    lines.append("\t\tconst char *b = name;")
    lines.append("\t\twhile (*a && *a == *b) { ++a; ++b; }")
    lines.append("\t\tif (*a == 0 && *b == 0) return &kEntries[i];")
    lines.append("\t}")
    lines.append("\treturn nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace %s" % namespace)
    lines.append("")
    pathlib.Path(out_path).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    total = sum(f.stat().st_size for f in files)
    print("embedded %d kernels, %d bytes -> %s" % (len(files), total, out_path))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(usage=__doc__)
    ap.add_argument("--namespace", default="avbd_kernels")
    ap.add_argument("src_dir")
    ap.add_argument("out_path")
    a = ap.parse_args()
    emit(a.src_dir, a.out_path, a.namespace)
