#!/usr/bin/env python3
"""Generate the AVBD Vulkan dispatcher's binding table from slangc reflection.

The Lean codegen already annotates every buffer with [[vk::binding(n, 0)]],
so each kernel's descriptor layout is fully described by the .refl.json that
`slangc -reflection-json` emits alongside the .spv. Deriving the table from
that instead of hand-writing it means the dispatcher cannot drift from the
kernels -- if Lean adds, removes or reorders a buffer, this regenerates.

Emits a C++ include consumed by src/code/slang_solver/AvbdSolverVk.cpp.

Usage:
    python gen_avbd_kernel_table.py --build-dir build --out AvbdKernelTable.inc \
        vbd_init vbd_solve_apply ...
"""

import argparse
import json
import os
import sys

# slangc reflection "kind"/"baseShape" -> the VkDescriptorType the dispatcher
# must bind. Everything the AVBD kernels declare is either a (RW)StructuredBuffer
# or a ConstantBuffer; anything else is unexpected and should fail loudly rather
# than be silently bound as the wrong type.
STORAGE = "VK_DESCRIPTOR_TYPE_STORAGE_BUFFER"
UNIFORM = "VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER"


def classify(param):
    """Return (descriptor_type, readonly) for one reflected parameter."""
    t = param["type"]
    kind = t.get("kind")
    if kind == "constantBuffer":
        return UNIFORM, True
    if kind == "resource":
        shape = t.get("baseShape")
        if shape != "structuredBuffer":
            raise ValueError(
                "unsupported resource shape %r on %r" % (shape, param["name"]))
        # Slang reports RWStructuredBuffer with access "readWrite"; a plain
        # StructuredBuffer omits the field or reports "read".
        return STORAGE, t.get("access", "read") != "readWrite"
    raise ValueError("unsupported parameter kind %r on %r" % (kind, param["name"]))


def parse(path, kernel):
    with open(path) as f:
        refl = json.load(f)

    params = []
    for p in refl.get("parameters", []):
        binding = p.get("binding", {})
        if binding.get("kind") != "descriptorTableSlot":
            raise ValueError(
                "%s: parameter %r has binding kind %r, expected "
                "descriptorTableSlot -- the kernel is probably using push "
                "constants or a different set" % (kernel, p["name"], binding.get("kind")))
        dtype, readonly = classify(p)
        params.append({
            "name": p["name"],
            "index": binding["index"],
            "type": dtype,
            "readonly": readonly,
        })

    params.sort(key=lambda b: b["index"])

    # Bindings must be dense from 0: the dispatcher allocates one descriptor
    # per slot and a gap would silently misalign every later binding.
    expected = list(range(len(params)))
    actual = [b["index"] for b in params]
    if actual != expected:
        raise ValueError(
            "%s: binding indices %s are not dense from 0" % (kernel, actual))

    entries = refl.get("entryPoints", [])
    if not entries:
        raise ValueError("%s: reflection has no entryPoints" % kernel)
    tg = entries[0].get("threadGroupSize")
    if not tg:
        raise ValueError("%s: entry point has no threadGroupSize" % kernel)

    uniforms = [b for b in params if b["type"] == UNIFORM]
    if len(uniforms) > 1:
        raise ValueError(
            "%s: %d constant buffers, dispatcher assumes at most one"
            % (kernel, len(uniforms)))

    return {
        "name": kernel,
        "entry": entries[0].get("name", "main"),
        "threadgroup": tg,
        "bindings": params,
        # -1 when the kernel takes no params block (e.g. spring_force).
        "params_binding": uniforms[0]["index"] if uniforms else -1,
    }


def emit(kernels, out_path, build_dir, namespace="avbd_table"):
    lines = []
    w = lines.append
    stage = namespace[:-len("_table")] if namespace.endswith("_table") else namespace
    guard = "CLOTH_%s_KERNEL_TABLE_INC" % stage.upper()
    if namespace == "avbd_table":
        w("// GENERATED by tests/slang_validate/gen_avbd_kernel_table.py -- DO NOT EDIT.")
        w("//")
        w("// Descriptor bindings for each AVBD compute kernel, read out of the")
        w("// slangc -reflection-json companion to each .spv. Regenerate with:")
        w("//     make -C tests/slang_validate avbd-table")
    else:
        w("// GENERATED by kernels/avbd/gen_avbd_kernel_table.py --namespace %s -- DO NOT EDIT." % namespace)
        w("//")
        w("// Descriptor bindings for each %s compute kernel, read out of the" % stage)
        w("// slangc -reflection-json companion to each .spv. Regenerate with:")
        w("//     kernels/%s/gen.sh" % stage)
    w("")
    w("#ifndef %s" % guard)
    w("#define %s" % guard)
    w("")
    w("namespace cloth {")
    w("namespace %s {" % namespace)
    w("")
    w("struct BindingDesc {")
    w("\tconst char* name;")
    w("\tuint32_t binding;")
    w("\tVkDescriptorType type;")
    w("\tbool readonly;")
    w("};")
    w("")
    w("struct KernelDesc {")
    w("\tconst char* name;          // basename; <name>.spv in the module dir")
    w("\tconst char* entry;         // SPIR-V entry point")
    w("\tuint32_t threadgroup[3];")
    w("\tconst BindingDesc* bindings;")
    w("\tuint32_t nBindings;")
    w("\tint32_t paramsBinding;     // -1 when the kernel takes no params block")
    w("};")
    w("")

    for k in kernels:
        w("static const BindingDesc kBindings_%s[] = {" % k["name"])
        for b in k["bindings"]:
            w('\t{ "%s", %d, %s, %s },'
              % (b["name"], b["index"], b["type"],
                 "true" if b["readonly"] else "false"))
        w("};")
        w("")

    w("static const KernelDesc kKernels[] = {")
    for k in kernels:
        tg = k["threadgroup"]
        w('\t{ "%s", "%s", { %d, %d, %d }, kBindings_%s, %d, %d },'
          % (k["name"], k["entry"], tg[0], tg[1], tg[2],
             k["name"], len(k["bindings"]), k["params_binding"]))
    w("};")
    w("")
    w("static const uint32_t kNumKernels ="
      " sizeof(kKernels) / sizeof(kKernels[0]);")
    w("")
    w("} // namespace %s" % namespace)
    w("} // namespace cloth")
    w("")
    w("#endif // %s" % guard)

    text = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", newline="\n") as f:
        f.write(text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", required=True,
                    help="directory holding <kernel>.refl.json")
    ap.add_argument("--out", required=True)
    ap.add_argument("--namespace", default="avbd_table",
                    help="inner namespace under cloth:: (default avbd_table)")
    ap.add_argument("kernels", nargs="+")
    args = ap.parse_args()

    parsed = []
    for k in args.kernels:
        path = os.path.join(args.build_dir, k + ".refl.json")
        if not os.path.exists(path):
            sys.exit("missing reflection for %s: %s\n"
                     "run `make -C tests/slang_validate spirv` first" % (k, path))
        try:
            parsed.append(parse(path, k))
        except (ValueError, KeyError) as e:
            sys.exit("reflection error: %s" % e)

    emit(parsed, args.out, args.build_dir, args.namespace)
    total = sum(len(k["bindings"]) for k in parsed)
    print("wrote %s: %d kernels, %d bindings" % (args.out, len(parsed), total))


if __name__ == "__main__":
    main()
