// The AVBD kernel binding table, unchanged from cloth-dynamics, read through
// RenderingDevice's enums.
//
// kernels/avbd/AvbdKernelTable.inc is generated by cloth-dynamics
// (tests/slang_validate/gen_avbd_kernel_table.py) from slangc's reflection of
// each kernel, and it spells descriptor types with Vulkan's names. The table is
// backend-neutral in substance -- a binding index, a name, uniform-or-storage,
// read-only or not -- so rather than fork it, this header gives those two
// names the RenderingDevice values from rd_enums.h and includes the file
// byte-for-byte. Regenerate the .inc upstream; never edit it here.
#pragma once

#include <cstdint>

#include "rd_enums.h"

using VkDescriptorType = int;
constexpr int VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER = rdc::UNIFORM_TYPE_UNIFORM_BUFFER;
constexpr int VK_DESCRIPTOR_TYPE_STORAGE_BUFFER = rdc::UNIFORM_TYPE_STORAGE_BUFFER;

#include "../kernels/avbd/AvbdKernelTable.inc"
