// The drape (L-BFGS-B) kernel binding table, read through RenderingDevice's
// enums: kernels/drape/DrapeKernelTable.inc is generated by kernels/drape/gen.sh
// (gen_avbd_kernel_table.py --namespace drape_table) and spells descriptor
// types with Vulkan's names, which avbd_table.h maps onto rd_enums.h.
#pragma once

#include "avbd_table.h"

#include "../kernels/drape/DrapeKernelTable.inc"
