import Cloth.Avbd.AdjacencyKwise
import Cloth.Avbd.AdjacencySpring
import Plausible
import PlausibleWitnessDag

/-!
# `Cloth.Avbd.CsrProperties` — property and falsifiability tests for the CSR build

`AdjacencyKwise` and `AdjacencySpring` pin `CsrAdj.build` with
`native_decide` on single fixtures. A fixture proves the build is right
*there*; it says nothing about the build in general, and the failure
mode that matters is not a crash — a wrong `role` silently makes every
gather kernel read the wrong per-constraint slot (`[K * c + role]`) and
produce plausible-but-wrong forces.

This module adds the two rungs above the fixtures:

* **Property** (`plausible`) — the invariants quantified over generated
  meshes rather than asserted on one.
* **Falsifiability** (`plausible-witness-dag`) — a deliberately broken
  build must be *caught*. A property suite that passes because it
  cannot see the bug is worse than no suite, so the round-trip property
  is re-run against a role-dropping build and required to produce a
  witness.

The ladder shape (`walkSteps` / `finBound` / `numInst`) is the same one
`witness-cpp` mirrors on the C++ side, so a property stated here and
the corresponding C++ check escalate the same way.
-/

namespace Cloth.Avbd.CsrProperties

open Cloth.Avbd.AdjacencyKwise

/-! ## Well-formedness predicates

All Bool-valued so `plausible` can decide them directly. -/

/-- Constraint lists generated by property testing may name vertices
outside `[0, nVerts)`; clamp so every generated mesh is meaningful
rather than discarded. -/
def clampMesh (nVerts : Nat) (cs : List (List Nat)) : List (List Nat) :=
  if nVerts = 0 then [] else cs.map (fun inc => inc.map (fun v => v % nVerts))

/-- `offsets` has length `nVerts + 1`, starts at 0, and is monotone. -/
def offsetsWellFormed (nVerts : Nat) (cs : List (List Nat)) : Bool :=
  let csr := CsrAdj.build nVerts (clampMesh nVerts cs)
  let o := csr.offsets
  o.size == nVerts + 1
    && (o[0]! == 0)
    && (List.range nVerts).all (fun v => o[v]! ≤ o[v + 1]!)

/-- The last offset equals the total number of incidences, and the
payload arrays are exactly that long. -/
def totalIncidences (nVerts : Nat) (cs : List (List Nat)) : Bool :=
  let m := clampMesh nVerts cs
  let csr := CsrAdj.build nVerts m
  let total := m.foldl (fun acc inc => acc + inc.length) 0
  csr.offsets[nVerts]! == total
    && csr.cIdx.size == total
    && csr.role.size == total

/-- **The property that matters.** Every entry in vertex `v`'s slice
names a constraint whose `role`-th vertex really is `v` — which is
exactly what the gather kernels' `[K * c + role]` indexing relies on. -/
def rolesAddressTheRightVertex (nVerts : Nat) (cs : List (List Nat)) : Bool :=
  let m := clampMesh nVerts cs
  let csr := CsrAdj.build nVerts m
  (List.range nVerts).all fun v =>
    (List.range (csr.offsets[v + 1]! - csr.offsets[v]!)).all fun j =>
      let s := csr.offsets[v]! + j
      let c := csr.cIdx[s]!
      let r := csr.role[s]!
      match m[c]? with
      | none => false
      | some inc => match inc[r]? with
        | none => false
        | some w => w == v

/-! ## Property rung — invariants over generated meshes -/

-- Meshes are generated small: `plausible` shrinks toward the empty
-- mesh, and CSR bugs show up at tiny sizes if they show up at all.
#test ∀ (nVerts : Nat) (cs : List (List Nat)),
  offsetsWellFormed (nVerts % 8) cs = true

#test ∀ (nVerts : Nat) (cs : List (List Nat)),
  totalIncidences (nVerts % 8) cs = true

#test ∀ (nVerts : Nat) (cs : List (List Nat)),
  rolesAddressTheRightVertex (nVerts % 8) cs = true

/-! ## Falsifiability rung

A build that drops the role. `rolesAddressTheRightVertex` must reject
it; if this search ever reports `provablyNone`, that property has lost
its teeth and the gather kernels are unguarded. -/

/-- `CsrAdj.build` with every role forced to 0 — the silent
wrong-answer failure mode described at the top of this file. -/
def buildRoleDropped (nVerts : Nat) (cs : List (List Nat)) : CsrAdj :=
  let csr := CsrAdj.build nVerts cs
  { csr with role := csr.role.map (fun _ => 0) }

/-- Same check as `rolesAddressTheRightVertex`, against the broken
build. `false` means the broken build was caught on this mesh. -/
def brokenRolesAddressTheRightVertex (nVerts : Nat) (cs : List (List Nat)) : Bool :=
  let m := clampMesh nVerts cs
  let csr := buildRoleDropped nVerts m
  (List.range nVerts).all fun v =>
    (List.range (csr.offsets[v + 1]! - csr.offsets[v]!)).all fun j =>
      let s := csr.offsets[v]! + j
      let c := csr.cIdx[s]!
      let r := csr.role[s]!
      match m[c]? with
      | none => false
      | some inc => match inc[r]? with
        | none => false
        | some w => w == v

/-- Decode a search candidate into a small mesh.

Deterministic and total, so the witness search is reproducible: a
candidate index always denotes the same mesh. Arity is forced to ≥ 2
because at `K = 1` the role is always 0 and a role-dropping build is
genuinely indistinguishable — that is not a counterexample, it is a
degenerate case. -/
def decodeMesh (n : Nat) : Nat × List (List Nat) :=
  let nVerts := 2 + n % 3          -- 2..4 vertices
  let k := 2 + (n / 3) % 3         -- arity 2..4
  let nC := 1 + (n / 9) % 2        -- 1..2 constraints
  let seed := n / 18
  let mesh : List (List Nat) :=
    (List.range nC).map fun c =>
      (List.range k).map fun r => (seed + 3 * c + 5 * r) % nVerts
  (nVerts, mesh)

/-- A candidate is a witness when the broken build FAILS the property
on that mesh — i.e. the property successfully detected the bug. -/
def brokenBuildIsCaught (_lvl : PlausibleWitnessDag.Level) (n : Nat) : Bool :=
  let (nVerts, mesh) := decodeMesh n
  -- A mesh with a repeated vertex inside one constraint is degenerate
  -- (first-occurrence role is deliberate), so skip those.
  let noDupes := mesh.all (fun inc => inc.eraseDups.length == inc.length)
  noDupes && !(brokenRolesAddressTheRightVertex nVerts mesh)

/-- Deterministic readback: the first candidate below the bound that
catches the broken build. -/
def readbackMesh (steps : Nat) : PlausibleWitnessDag.Readback (Nat × List (List Nat)) :=
  let found := (List.range steps).find? fun n =>
    brokenBuildIsCaught { idx := 0, walkSteps := steps, finBound := steps, numInst := 1 } n
  match found with
  | some n => { value := decodeMesh n, found := true, witnessIdx := n,
                budgetHit := false }
  | none => { value := (0, []), found := false, witnessIdx := 0,
              budgetHit := true }

/-- Run the falsifiability search. Prints the mesh that catches the
role-dropping build, or reports that none was found — which would mean
the property is blind. -/
def checkFalsifiability : IO Unit := do
  let (mesh, idx, trace) ← PlausibleWitnessDag.resolve
    "role-dropping CSR build is caught by rolesAddressTheRightVertex"
    brokenBuildIsCaught readbackMesh
  IO.println s!"[csr-falsifiability] witness idx={idx} mesh={mesh}"
  IO.println s!"[csr-falsifiability] {repr trace}"

end Cloth.Avbd.CsrProperties
