// GENERATED by `lake exe emit_ggml` from lean/Ggml/SlangCodegen/Common.lean.
// Do not edit; regenerate with kernels/ggml/gen.sh.
//
// The word layout of one params slot and the descriptor layout every
// ggml-rd kernel shares. Strides and offsets are in elements.
#pragma once

#include <cstdint>

namespace ggml_rd {

constexpr uint32_t kWordsPerSlot = 64;
constexpr uint32_t kSlotBytes = 256;
constexpr uint32_t W_KERNEL = 0;
constexpr uint32_t W_DST = 1;
constexpr uint32_t W_SRC0 = 10;
constexpr uint32_t W_SRC1 = 19;
constexpr uint32_t W_SRC2 = 28;
constexpr uint32_t T_NE = 0;
constexpr uint32_t T_NB = 4;
constexpr uint32_t T_OFF = 8;
constexpr uint32_t W_OP_PARAMS = 37;
constexpr uint32_t N_OP_PARAMS = 16;
constexpr uint32_t W_DERIVED = 53;
constexpr uint32_t N_DERIVED = 11;
constexpr uint32_t W_THREADS = 53;
constexpr uint32_t W_GROUPS_X = 54;
constexpr uint32_t kMaxGroupsPerDim = 65535;

// Descriptor layout (set, binding).
constexpr uint32_t SET_TENSORS = 0;
constexpr uint32_t SET_SLOT = 1;
constexpr uint32_t B_PARAMS = 0;
constexpr uint32_t B_SRC0 = 1;
constexpr uint32_t B_SRC1 = 2;
constexpr uint32_t B_SRC2 = 3;
constexpr uint32_t B_DST = 4;
constexpr uint32_t B_SLOT = 0;

} // namespace ggml_rd
